# Headless Service
apiVersion: v1
kind: Service
metadata:
  name: spark-driver
  namespace: airflow
spec:
  clusterIP: None
  selector:
    component: worker
  ports:
  - name: spark-driver-ui-port
    port: 4040
    targetPort: 4040
  - name: blockmanager
    port: 7777
    targetPort: 7777
  - name: driver
    port: 2222
    targetPort: 2222
